---
abstract: 'allows for basic data dumping and introspection.'
author:
  - "[ 'Paul Seamons <paul@seamons.com>',  'Russel Fisher <geistberg@gmail.com>' ]"
build_requires:
  Test::More: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Debug
requires:
  Apache: 0
  Apache2::RequestRec: 0
  Apache2::RequestUtil: 0
  Apache::RequestUtil: 0
  B::Deparse: 0
  Carp::Heavy: 0
  Data::Dumper: 0
  Exporter: 0
  base: 0
  perl: v5.8.0
  strict: 0
version: 0.002
